apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: karchiz-scraper
spec:
  selector:
    matchLabels:
      app: karchiz
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
