name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
      - run: black --check .

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: py-actions/py-dependency-check@v1
      - run: bandit -r src -ll

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pytest --cov=src --cov-branch --cov-report=xml
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - run: docker build -f docker/scraper.Dockerfile -t ghcr.io/aliazimid/karchiz-scraper:latest .
